### PR TITLE
ID-88 Replace MySQL with lowdb

### PR DESCRIPTION
**Pull request by Plypy**
This PR replaced MySQL with light-weight json-based solution `lowdb`.

What's more it also solved ID-16 to support unicode.

To use this update, 

```
globalnavbar$: cp lib/db.example.json lib/db.json
globalnavbar$: npm install
```

### CODE REVIEW

**Comment by robbyoconnor** [comment]
Why are not using mongo?

**Comment by robbyoconnor** [comment]
Why are we using this over mongo?

**Comment by elliottwilliams** [comment]
I would guess the idea behind using lowdb over mongo is that the data stored here isn't user data, it's admin-specified config data. So a flat JSON file might be favorable, making it easier to edit / transfer configs.

I also think it makes more sense to just use Mongo here though—one less dependency to worry about, one more piece of our app code that can be reused. But it's not super-important either way.

**Comment by Plypy** [comment]
To clear the confusion, here is why.

1. You may have noticed that the number of requests for navbar is far more than for Dashboard itself, as it will serve lots of sites. And efficiency is thus important. By using plain JSON based solution, there will be less disk I/O, as the file will be stored in memory.

2. Besides the data of navbar isn't big, we don't need to utilize DB's powerful searching ability.

3. It's easier to maintain not only for developers but also for admins.

**Comment by downeym** [comment]
Happy to see this being made more efficient. Thanks!

**Comment by robbyoconnor** [comment]
I spoke with @Plypy yesterday evening (my time) and he explained it -- I like the idea :+1:

**Comment by elliottwilliams** [comment]
I'm also a fan. +1

**Comment by Plypy** [comment]
Caveat here: In this simple solution, there isn't dirty write sync, which means even if you have edited the config file directly, the app won't reflect this change as its cache won't be updated. Unless you reboot dashboard, so don't directly change `db.json`.

**Pull request merged**
